### ISSUE TITLE
URL issue on v1.x.x

### ISSUE THREAD

**Issue by UnAfraid** [NodeBB/nodebb-plugin-featured-threads#12]
Hello,

I've notice that url generation's variable {relative_path} was not replaced i changed it with {config.relative_path} and it worked for me
within featured-topics-sidebar.tpl

``` javascript
-           <strong><a href="{relative_path}/topic/{topics.slug}">{topics.title}</a></strong>
+           <strong><a href="{config.relative_path}/topic/{topics.slug}">{topics.title}</a></strong>
```

It seems that {topics.relativeTime} also doesn't works either.

**Comment by gnimmelf** [comment]
I second that issue.

**Comment by PongoPygmaeus** [comment]
Neither relative nor absolute dates seem to work. Both show "invalid date" in the card.
